# Usa un'immagine Node.js compatibile con ARM
FROM node:16-bullseye

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file di configurazione
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il codice sorgente
COPY . .

# Esponi la porta del backend
EXPOSE 5500

# Comando per avviare il server
CMD ["npm", "start"]
