# Usa un'immagine Node.js compatibile con ARM
FROM node:16-bullseye as build

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file di configurazione
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il codice sorgente e costruisci l'app
COPY . .
RUN npm run build

# Usa un server NGINX per servire l'app
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Esponi la porta del frontend
EXPOSE 80

# NGINX si avvia automaticamente come demone
